name: Go Build for Multiple Platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ] # Multiple OS platforms
        arch: [ amd64 ] # Architecture

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.1'

    - name: Build the project
      run: |
        # Determine GOOS based on matrix OS
        if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
          GOOS=linux
        elif [ "${{ matrix.os }}" = "windows-latest" ]; then
          GOOS=windows
        elif [ "${{ matrix.os }}" = "macos-latest" ]; then
          GOOS=darwin
        fi

        GOARCH=${{ matrix.arch }}

        # Create the build directory and build the project
        mkdir -p build/${GOOS}-${GOARCH}
        go build -v -o build/${GOOS}-${GOARCH}/myapp ./...

    - name: Test
      run: go test -v ./...

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: tmf-timetable-backend-${{ matrix.os }}-${{ matrix.arch }}
        path: build/${{ matrix.os == 'ubuntu-latest' && 'linux' || matrix.os == 'windows-latest' && 'windows' || matrix.os == 'macos-latest' && 'darwin' }}/${{ matrix.arch }}
