name: Go Build for Multiple Platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ] # Multiple OS platforms
        include:
          - os: ubuntu-latest
            arch: amd64
          - os: windows-latest
            arch: amd64
          - os: macos-latest
            arch: amd64

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.1'

    - name: Build the project
      run: |
        GOOS=${{ matrix.os | cut -d'-' -f1 }} \
        GOARCH=${{ matrix.arch }} \
        mkdir -p build/${GOOS}-${GOARCH} \
        go build -v -o build/${GOOS}-${GOARCH}/myapp ./...

    - name: Test
      run: go test -v ./...

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: myapp-${{ matrix.os }}-${{ matrix.arch }}
        path: build/${{ matrix.os | cut -d'-' -f1 }}-${{ matrix.arch }}/
